import EmployeTemplate from "@/components/employeeTemplate";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Access By KAI",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
    <EmployeTemplate>
        {children}
    </EmployeTemplate>
    );
}
